name: MicroMart Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push User Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/user-service
          push: true
          tags: micromart/user-service:latest

      - name: Build and push Product Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/product-service
          push: true
          tags: micromart/product-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # For Kubernetes deployment (example using Google Cloud)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: micromart-cluster
          location: us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment/kubernetes/infrastructure/
          kubectl apply -f deployment/kubernetes/databases/
          kubectl apply -f deployment/kubernetes/services/
